### ISSUE TITLE
More sophisticated way to create dummy data

### ISSUE THREAD

**Issue by nicksellen** [yunity/yunity-core#103]
It would be super userful to have a simple way to create a bunch of dummy data, a few considerations:

- locations should be realistic
- can be rerun without dropdb/createdb cycle
- better way to run it (I'm currently using `shell_plus` with ipython and `%run yunity/management/commands/create_sample_data.py`

**Comment by nicksellen** [comment]
maybe using something like https://pypi.python.org/pypi/fake-factory

**Comment by c-w** [comment]
Look into `yunity.utils.tests.mock`
