### ISSUE TITLE
Resolve django warning about TEMPLATES

### ISSUE THREAD

**Issue by nicksellen** [yunity/yunity-core#105]
```
/code/yunity/yunity-core/env/lib/python3.4/site-packages/django/template/utils.py:37: RemovedInDjango110Warning: You haven't defined a TEMPLATES setting. You must do so before upgrading to Django 1.10. Otherwise Django will be unable to load templates.
  "unable to load templates.", RemovedInDjango110Warning)
```

**Comment by c-w** [comment]
Given that we're API-only, we never need templates. How do we suppress/fix this warning in this context?

**Comment by nicksellen** [comment]
Presumably just creating a TEMPLATES setting in config with nothing in it? I'll try it at some point in the future unless someone does it before me...

**Comment by tiltec** [comment]
I've no idea if it's still there, but the card is so old - would like to close it without investigation. Feel free to re-open if necessary.
