### ISSUE TITLE
Rethink Session authentication

### ISSUE THREAD

**Issue by NerdyProjects** [yunity/yunity-core#106]
Session authentication uses normal django sessions right now.

These are also made available to the client javascript for the realtime parts to work (so we authenticate the websocket via the same session id).

We might switch to API tokens instead and might also want to use a separate token just for the realtime library.

**Comment by tiltec** [comment]
@NerdyProjects is this still a thing? I'm just looking through the issues, haven't dived in.

**Comment by nicksellen** [comment]
I think normal django session auth is ok for now. It's simpler to think about because it is more common. The browser is handling a lot of stuff for you. With tokens, you end up handling things a lot more...

**Comment by NerdyProjects** [comment]
Sorry, going to add djangorestframework-jwt now as we have a usecase for cross origin requests (which is quite common) to get lars temporary frontend running.

**Comment by nicksellen** [comment]
I suggest storing the JWT in a cookie for browsers, see https://stormpath.com/blog/where-to-store-your-jwts-cookies-vs-html5-web-storage.

CORS makes security much more complicated, as the same origin policy is one part of preventing CSRF attacks (https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)).

JWT (cookie or localStorage) + CORS greatly increases the chance a security vulnerability.

For these reasons I would stick to traditional cookie + server sessions. If needing non-browser API access, then you can add additional authentication methods (e.g. basic auth), that can be active on the same endpoints, or add seperate endpoints (in the BFF style - http://samnewman.io/patterns/architectural/bff/).

**Comment by nicksellen** [comment]
... and you can always just have a proxy backend that serves up the alternative frontend, and proxies the /api requests to the real backend.

**Comment by NerdyProjects** [comment]
Lars frontend is using direct ajax calls and he has problems setting up the proxy for localhost/api to dev.yunity.org as django always redirects. Maybe header rewriting could help... Otherwise, I don't find information regarding CSRF attack vulnerability for jwt as the token will not have a way to leave the app?

http://stackoverflow.com/questions/27067251/where-to-store-jwt-in-browser-how-to-protect-against-csrf (bearer scheme would be my choice - even before reading that).

Do you still - except the slight overhead of frontent code for jwt handling - see downsides for this approach? We would get rid of the csrf tokens as well so simplify there again.
The reason really is just "make it work" for the case with the other frontend here (will be published tomorrow in the https://github.com/yunity/yunity-MVP-PHP_JS-Frontend repo (the name is a bit misleading...)

**Comment by NerdyProjects** [comment]
Okay, after some more reading I give up here and do the simpler approach of using corsheaders django package. Thank you for pointing me in the direction of not just doing, this topic should be reconsidered before launch as it is really not a simple problem.

**Comment by NerdyProjects** [comment]
All of the necessary things have already been inplace. d53f2a9aae9f256ec just changes some settings for cookie generation. Readme describes necessary steps to use the API with cross origin. XSS/CSRF implications should still be checked before launch...

**Comment by nicksellen** [comment]
I would still not use CORS, on the basis on simplicity. The biggest security issues are between the interaction between browser and backend, and keeping this as closed down and minimal as possible minimises risk of a hole.

See https://github.com/pillarjs/understanding-csrf#disable-cors - although with CSRF tokens and HttpOnly (and Secure too), it should be ok. I would add a Content Security Policy too.

... but nothing beats simplicity, complete with out-the-box support ...

**Comment by NerdyProjects** [comment]
I don't get the out-of-the-box-support thing as the current state did not need more than 3 lines of configuration (of which we had 2 already in place). In general, I agree to what you are saying. This still leaves the issue: How do we support 3rd party frontends running in a browser? Maybe we should delay this discussion and for now just see the current settings as dev-settings? :D

**Comment by nicksellen** [comment]
The added complexity isn't turning the CORS headers on, but being really clear about the implications for CSRF/XSS/etc, and then (probably) having to maintain a whitelist of allowed CORS orgins.

> How do we support 3rd party frontends running in a browser?

I simply would not, why is this a goal? Cross origin browser limitations are a useful asset for security.

It's super simple when there is just 1 domain, and cookies, sessions, requests, are all using that domain.

> see the current settings as dev-settings

Which introduces differences between dev and production setups, which I like to avoid as much as humanly possible, or you can end up debugging web server/frontend/domain problems which only occur after deployed.

> he has problems setting up the proxy for localhost/api to dev.yunity.org as django always redirects

I would not suggest developing against the backend running at dev.yunity.org. It could change at any time, and become incompatible with someones work (it has already switched from master branch to tvp branch), and might not always be available.

A locally running backend should be possible to run without too much trouble. Some more love could be put into the docker setup to enable a whole backend to run with docker... (using docker-compose, or the new docker swarm features). https://yunity.atlassian.net/wiki/display/YUN/Docker+Setup.

**Comment by NerdyProjects** [comment]
Okay. Thanks for clarification, then we are on the same side. The point "I simply would not" support 3rd party frontends running in a browser boils down to we don't need all of that. I will revert my changes and disable CORS which then should not be necessary anymore at all. I will also communicate with lars to see what he needs for the backend side.

**Comment by nicksellen** [comment]
Close this now? I don't think there are any changed proposed any more?

**Comment by tiltec** [comment]
Stay with sessions for the time being, I'd say.
