### ISSUE TITLE
Deploy slackin to allow public invite access

### ISSUE THREAD

**Issue by nicksellen** [yunity/yunity-core#111]
See https://github.com/rauchg/slackin

**Comment by NerdyProjects** [comment]
We want everybody to be able to signup for our slack and it seems that we want that soon. Anybody willing to install?

**Comment by NerdyProjects** [comment]
@bbew wants to be informed when done :)

**Comment by NerdyProjects** [comment]
So we decided against heroku because it did not work out of the box, I will do

**Comment by tiltec** [comment]
It works, set up by @NerdyProjects and integrated on http://project.yunity.org/what-we-need by @tiltec
