### ISSUE TITLE
As a developer, I want to understand the need for concrete model inheritance (vs abstract)

### ISSUE THREAD

**Issue by nicksellen** [yunity/yunity-core#113]
https://docs.djangoproject.com/en/1.8/topics/db/models/#model-inheritance says:

    Often, you will just want to use the parent class to hold information that you don’t want to have to type out for each child model. This class isn’t going to ever be used in isolation, so Abstract base classes are what you’re after.

Isn't that our use case?

And a few peoples thoughts from the interwebs:
- https://jacobian.org/writing/concrete-inheritance/
- http://stackoverflow.com/questions/23466577/should-i-avoid-multi-table-concrete-inheritance-in-django-by-any-means
- http://charlesleifer.com/blog/django-patterns-model-inheritance/ (added in edit)

The main use case for concrete inheritance seems when you want to query one of the superclasses directly (e.g. `MapItem`), but I don't think we need this do we? (as this kind of search is by elasticsearch). And _I think_ this would only return you the fields from `MapItem` not the actual lowest level class.

I'm not suggesting we make any changes, just understanding/information.

**Comment by c-w** [comment]
One thing to keep in mind is that abstract classes can't be the target of foreign keys e.g. see `Interaction.changed`.
