### ISSUE TITLE
remove bower in frontend repos

### ISSUE THREAD

**Issue by maackle** [yunity/yunity-core#119]
we can use npm for all dependencies

**Comment by nicksellen** [comment]
http://mobileangularui.com/ which we use on the mobile app doesn't work properly when used as an npm dependency.

https://www.npmjs.com/package/mobile-angular-ui has an invalid version "0.0.0" and when imported/required does not bind itself correctly (it assumes `this` is `window` IIRC).

https://github.com/mcasimir/mobile-angular-ui/issues/289 tracks the issue to some extent, we can probably poke them on this at some point.

**Comment by nicksellen** [comment]
This can be done now as we're not using mobile-angular-ui
