### ISSUE TITLE
As a user, I want to be able to communicate/chat with a group

### ISSUE THREAD

**Issue by c-w** [yunity/yunity-core#12]
This is a port of the "message wall" on the store pages of the foodsharing site.

We want a general-purpose widget that provides an access-controlled messaging wall. On this wall, users can post messages that are visible to a subset of users defined by membership in a particular group, e.g. "food-sharing store X" or "free concert event Y".

**Comment by Sliverriver** [comment]
i want to be able to leave and join the group chat.
or autojoin/leaving of chats if you join/leave a store (maybe for store specifications?)

**Comment by NerdyProjects** [comment]
@Sliverriver I think your comment better fits the realtime messaging chat as this story is not related to a live-chat.

**Comment by Sliverriver** [comment]
sorry i misunderstood - yes you are right.
