### ISSUE TITLE
Federate with other decentralized social networks

### ISSUE THREAD

**Issue by jaywink** [yunity/yunity-core#121]
The true power of decentralization comes not from building software that is decentralized, but building software that talks to other decentralized software as well.

There is strong effort in this direction with the [SocialWG W3C working group](https://www.w3.org/wiki/Socialwg) that is creating a standard for social applications to federate together. Strongly encourage someone from your group to follow this work.

There is also the diaspora* protocol, which has united three projects, [diaspora*](https://diasporafoundation.org), [Friendica](http://friendica.com/) and [Hubzilla](http://hubzilla.org), to federate together to form a network of [an estimated 80K active users](http://the-federation.info).

Strongly encourage your team to consider how federating over existing standard protocols could help not only your software to flourish, but also allow users to communicate to a wider world from the word go.

**Comment by butze7** [comment]
thank you very much for your input jaywink. The cooperation with other existing networks is a very important task for us. we will have a closer look on SocialWG W3C and diaspora very soon

**Comment by tiltec** [comment]
As @butze7 wrote, the diaspora* protocol is on our radar, and we are also interested in the SocialWG standard.
However, our minimum viable product specification goes in a different direction. We are in the process of replacing the software of www.foodsharing.de with yunity, as this is where we have the strongest connections to. Also, 10K active users depend on us.
From a development perspective, I would say it makes most sense to spin this off to a separate project, where we can explore the possibilities for goods-sharing that come with decentralized software.

**Comment by elf-pavlik** [comment]
:+1:

**Comment by NerdyProjects** [comment]
We already had a view on the diaspora implementation. The design is much simpler of what we are specifying here so it could only ever be a simple view on (mainly) public content. Did not look into the SocialWG so far.

From my point of view, sadly it does not make sense in the near future to have any of this implemented. When we are ready for interacting with other projects, we should look into what interesting projects use and do that as well for a start, although I'm strongly in favor of using something open.
