### ISSUE TITLE
Rethink database model in correlation with the MVP

### ISSUE THREAD

**Issue by NerdyProjects** [yunity/yunity-core#123]
The current database model is very abstract and general. As the MVP shows a clearer view on different parts (especially the group being a main thing from now on without current mapping on the database scheme), some people should gather and rethink the thing in general. Major parts should still be fine, some will not.

**Comment by NerdyProjects** [comment]
The database model is undergoing a complete redesign in correlation to the spec. It should not be considered stable or even (easily) migratable until this ticket is resolved.

**Comment by tiltec** [comment]
I would even say that the model isn't stable until the MVP is finished. I would close this issue.
