### ISSUE TITLE
Fix swagger doc path parameters

### ISSUE THREAD

**Issue by NerdyProjects** [yunity/yunity-core#130]
The generated path should be like ../{parameter}/... this only works for some parts.

See flask_swagger.py:191 and fix that regex :) (it is already quite tied to our generator and for me it sounds okay to stay more or less like that)

**Comment by nicksellen** [comment]
Fixed in https://github.com/yunity/yunity-core/commit/9ae7b6ac9ad3d2357ae5cafe277e432a965f419e
