### ISSUE TITLE
Add location to items

### ISSUE THREAD

**Issue by NerdyProjects** [yunity/yunity-core#134]
An item should be showable on a map - think about a good way to store them in the model and implement that.

**Comment by tiltec** [comment]
Currently, food baskets are the only type of items we have. A food basket has a single location. The user should be able to search for nearby food baskets. The location of all food baskets are shown on a map.

**Comment by raphaelfellmer** [comment]
yeahh and dont forget that future items still have always one current
position but can have several positions where they have been in the past as
well as the users who "owned" the item part time ;)

2016-01-05 16:18 GMT+01:00 Tilmann Becker <notifications@github.com>:

**Comment by tiltec** [comment]
Currently, we don't allow changes to location, owner and description of an item. This is an additional task. It could be solved with a versioning system in the model, which I would like to discuss to have a better understanding of the implications.
