### ISSUE TITLE
Collect authorization user stories

### ISSUE THREAD

**Issue by NerdyProjects** [yunity/yunity-core#136]
There are already things where authorization is unclear:
user first/last name
user email

group editing (-> still missing group roles)

**Comment by NerdyProjects** [comment]
This needs more input from the product team, maybe after authorization and permissions is discussed further.

**Comment by tiltec** [comment]
Is in process, results will be collected in the wiki:
https://yunity.atlassian.net/wiki/display/YUN/Permissions
