### ISSUE TITLE
Discuss Permission model

### ISSUE THREAD

**Issue by NerdyProjects** [yunity/yunity-core#143]
Discussion results from a discussion between @nicksellen and @me:

The permission model should be able to solve the following questions

- "can user <verb> this object?" : boolean (single ressource permission query)
- "give me the verbs the user can do on the object" (to know what actions are possible on a resource)
- "given an object, who can <verb> it" (to be able to list, who can do what on an object)

And - in special use cases, for example for administrative purposes:

- "given a user, give me a list of objects they can <verb>"
- "give me a list of objects that user can <verb>"
- "given an object, what verbs are available for it"
- give me a list of things, and join the permissions I have on them"

Discussion for the latter use cases is appreciated.

Permissions are granted or derived either

- through implicit permissions by being a member of something (e.g. a member of a group or an event always has the permission to see this specific thing)
- through explicitly granted permissions by having a team membership that includes some permissions (e.g. group welcoming teams, report teams)
- or through explicit settings on the subjected object (public event, hidden user profile (that may display different information depending on the connection of two users), wall for members only)

**Comment by NerdyProjects** [comment]
This task is not really relevant anymore as there has more happened. Will be written down accordingly by me soon.

**Comment by tiltec** [comment]
"Django Guardian" is recommended by DRF and provides object level permissions https://github.com/django-guardian/django-guardian

**Comment by nicksellen** [comment]
I would suggest we ignore what me and @NerdyProjects discussed before, it was in the context of complex hierarchy of permissions ala foodsharing.de. I think for simple international foodsharing MVP it is almost all irrelevant and way too complex.

Close this task?

**Comment by tiltec** [comment]
Yes, let's close it and hope to remember it when it's needed.
