### ISSUE TITLE
Interview Request from Transformap

### ISSUE THREAD

**Issue by thoka** [yunity/yunity-core#144]
Hi @nicksellen @NerdyProjects @maackle @c-w @Sliverriver !

In the context of [transformap](http://discourse.transformap.co) I would like to do an interview with you about your technical vision and roadmap. 
I would be happy if you like to join our discourse for this purpose or tell me some other place, where we could do that interview.

**Comment by tiltec** [comment]
Hi @thoka, very cool project! I'm still digging into transformap, but it's definitely interesting to us! 
Can you link me to an overview articles of transformap, or a howto? I'd like to show it to your non-developer members.

Currently, we are working on a foodsharing.de successor platform, which will also spread to Italy, France, Britain, Poland, Russia and other countries with foodsharing and -saving communities.

If you would like to know more about yunity, feel free to join our Slack chat (https://project.yunity.org/join-the-team on the bottom) and have a look at the Roadmap (https://yunity.atlassian.net/wiki/display/YUN/Roadmap)

Love, Tilmann

**Comment by tiltec** [comment]
(I added a contact card to our Trello board: https://trello.com/c/aoMWVkTT/84-contact-transformap)
closing

**Comment by almereyda** [comment]
Hi @tiltec you can find a pretty recent documentation about TransforMap by @AdrienLab at https://discourse.transformap.co/t/crowd-mapping-alternative-economies-the-transformap-proposal/765
