### ISSUE TITLE
API: Search endpoint

### ISSUE THREAD

**Issue by tiltec** [yunity/yunity-core#169]
Find all things by plain-text search: groups, stores, users.
Either implemented as simple parameter for each endpoint: `GET /api/users/?search=<string>` (supported by framework).
Or a catch-all `GET /api/search` endpoint, with considerably more flexibility and more coding.

**Comment by D0nPiano** [comment]
I think, in the long run, an /api/search endpoint makes more sense, since the first solution sounds like 3 ajax requests (user, group, store) per character to me, if we wanted to do the autocomplete. I'd leave it to @Sneezoo and you though.

**Comment by Sneezoo** [comment]
The advantage of searching by ressource-route is definitely more REST-style and makes stuff on backend much simpler than the `/api/search/` approach. `/api/search/` will make searching error-prone due to complicated queries.
**To sum up**: I would choose /api/users/<filter>=xyz

**Comment by nicksellen** [comment]
`/api/search` might make sense when/if there is an elasticsearch and we can reasonably search across all the types (for a *search everywhere* kind of UI).

For now per-type seems quite reasonable, maybe `/api/users/?q=foo`?
