### ISSUE TITLE
As a user, I want to describe who i am

### ISSUE THREAD

**Issue by neeljp** [yunity/yunity-core#19]

**Comment by c-w** [comment]
We have two options here:
- we can use the wall of the User/MapItem and have a convention that the first post is the description
- we add an explicit description column to the User/MapItem model

I'd actually be in favor of the later:
- no convention/"abuse"
- makes search easier: we might want to have full-text search on all descriptions of items (e.g. to find all users who like rock climbing or all food baskets that mention baklava) but not on all the walls of all items.

**Comment by NerdyProjects** [comment]
+1 to the later. don't reuse a thing for a completely different purpose :)

We may extend this discussion to the description of an Item - but as the item may change, a wall would be fine here.

One more question: Why not just use metadata for the user properties? We also have things like birthday, profile photo, ...

**Comment by tiltec** [comment]
The model changed in Mainz, I think we should have an explicit column for user details.
https://trello.com/c/d6p44LvP/52-u-2-as-a-user-i-want-to-view-and-edit-my-profile-so-that-i-can-tell-something-about-me-story-points

**Comment by tiltec** [comment]
Just seeing that this is only a small part of the profile. We will use wall posts for that:
https://trello.com/c/OmCUCh1B/51-w-1-as-a-user-i-want-to-write-text-posts-on-my-wall-so-i-can-share-informations
