### ISSUE TITLE
As a user, I want be able to mark other users as trusted

### ISSUE THREAD

**Issue by neeljp** [yunity/yunity-core#22]

**Comment by c-w** [comment]
Scenario: John wants to say that he trusts Mark because they know each other.

We can represent this in the model as follows.
- John creates a Feedback
- set `Feedback.about = Mark.id`
- set `Feedback.providedBy = John.id`
- set `Feedback.type = 'trust'`

**Comment by NerdyProjects** [comment]
An additional feature request here is having some plain text in addition. The feedback.type trust may also implicitly make the feedback message publicly readable.
