### ISSUE TITLE
As a user I want to communicate over a specific item

### ISSUE THREAD

**Issue by NerdyProjects** [yunity/yunity-core#30]

**Comment by tiltec** [comment]
It could be done by pinboard attached to an item.
Enable pinning/starring of items for clarity

**Comment by MartinSchott** [comment]
also i want to be able to send a message directly to the one who offered the item

**Comment by c-w** [comment]
We can represent both of these use-cases in our model via `MapItem.Wall` and `Chat` -- so I'd say that this is a front-end consideration for the view on Valuable: add a button to initiate a chat with all users in Valuable.administratedBy and add a post to the wall.
