### ISSUE TITLE
As a user, I want to see new items in real time without reloading the page

### ISSUE THREAD

**Issue by tiltec** [yunity/yunity-core#31]
If another user enters a new item, it should be displayed on the page without reloading.

**Comment by c-w** [comment]
Given the low number of interactions on the website, I don't think this is worth the added complexity. A simple implementation of refetching all the data every N minutes would get us most of the way there. Opinions?

**Comment by NerdyProjects** [comment]
For now, yes.

When we have decided how to do notifications this may map nicely anyway to the same scheme (e.g. when a user gets a notification on a specific foodbasket, we may also push it directly to him).

Anyway this does not solves the problem of a user scrolling around the map and getting live updates there. This may be even further deferred.
