### ISSUE TITLE
Implement multiple user chat

### ISSUE THREAD

**Issue by tiltec** [yunity/yunity-core#34]
Chat has a fixed set of users. Every user can write a message. All other users receive it.

**Comment by tiltec** [comment]
user story #12

**Comment by Sliverriver** [comment]
be able to leave/join a chat. be able to remove other users from chat.

**Comment by NerdyProjects** [comment]
We have different kinds of chat:
1 on 1 -> fixed chat.
multiple users (group chat): dynamically add/remove users, set name of chat
