### ISSUE TITLE
As a smartphone user, I want to receive real time notifications and chat.

### ISSUE THREAD

**Issue by tiltec** [yunity/yunity-core#42]
Should save battery and be reliable. Possible candidates: crossbar.io sockets, Google Cloud Messaging

**Comment by MartinSchott** [comment]
should have push notifications for messages, events that begin soon, requests for my items, answers to my item requests

**Comment by NerdyProjects** [comment]
There are multiple scenarios here:
- Webapp compatibility -> notifications on realtime channel
- General app compatibility -> may have the realtime channel open at first but a mobile optimized version later (investigate long-polling vs. websockets for apps)
- Specific app compatibility: Add GCM / IOS / Windows Phone integrated message channels when an app is available. This is _the only_ battery and data efficient possibility. Think about privacy as well, maybe use only for notification to actively request data.
