### ISSUE TITLE
as a user i want to rate the other user's reliability

### ISSUE THREAD

**Issue by Sliverriver** [yunity/yunity-core#51]
If i want to be able to give feedback about the experience with other users . if they showed up as promised or just didn't appear.

**Comment by c-w** [comment]
Scenario: John advertised a BananaFoodbasket. Peter requested the basket but didn't show up for the pickup.

Representation:
- create Feedback
- Feedback.about = (
    SELECT id
    FROM Participate
    WHERE target = BananaFoodbasket.id AND requester = Peter.id
)
- Feedback.providedBy = John.id
- Feedback.type = 'noShow'


Scenario: John requested a musician for his MaloDiscoSoup. Peter said he'd do it and delivered a great performance.

Representation:
- create Feedback
- Feedback.about = (
    SELECT id
    FROM Participate
    WHERE target = MaloDiscoSoup.id AND requester = Peter.id
)
- Feedback.providedBy = John.id
- Feedback.type = 'awesome'
