### ISSUE TITLE
as a user i want to be able to report abuse

### ISSUE THREAD

**Issue by Sliverriver** [yunity/yunity-core#54]
as a user i want to be able to report abuse, if i have been insulted or got sexually related messages

**Comment by c-w** [comment]
Scenario: John wrote an insulting message to Nick. Nick wants to report this.

Representation:
- create Feedback
- Feedback.reportedBy = Nick.id
- Feedback.about = John.id
- Feedback.type = 'insult'
- Feedback.arbitratedBy = GeneralModeratorsList

**Comment by NerdyProjects** [comment]
Which brings up the point, how to define these "GeneralModeratorsList".
An opportunity "GeneralModerators" with participants of type "Moderator"?

**Comment by NerdyProjects** [comment]
See spec in https://yunity.atlassian.net/wiki/display/YUN/Report+Module which makes this user story obsolete.
