### ISSUE TITLE
As a developer, I want to understand what a notification is

### ISSUE THREAD

**Issue by NerdyProjects** [yunity/yunity-core#61]
A user gets a notification ("bell"). What attributes does this have? When is it read? What does the user do with it?

**Comment by Sliverriver** [comment]
- as a user i would want to see who caused the notification and what the interaction was about.
- as a user i  want to see the context of the notification. (foodbasket, item , request for an item, comment on a discussion, etc., creation of an event)
- as a user i would want to click on the notification to get directly to the object causing the notification. 
as a user i would want to have control of the notification to remove it from the notificatoin bar or to have it generally expire so that the notification listing is not too long.
- i am uncertain if a user would wantto have a history of all notifications.
- as a user i might want to have it customisable for which types to recive notification bells.

**Comment by c-w** [comment]
One pragmatic way to implement this would be to have notifications as searches.

We can periodically execute the searches and diff the results. If the diff changes, we send a message to the user who registered the search.

There are several nice things about this:
- notifications are completely separate from the application code
- we can trivially move notifications to a separate fleet if we need to scale
- support for super complex notifications for free -- users can be notified on anything that can be searched on

Disadvantage:
- polling

**Comment by NerdyProjects** [comment]
@c-w I see this as a good first approach but would leave an option to create some notifications just when the event happens - e.g. something in an opportunity you participate in changes may generate immediate notifications. This just as a future use for now because for most things the periodic search looks fine

**Comment by raphaelfellmer** [comment]
We wrote down some cases (more than 50 ;-) when actually a user gets a notification, maybe that will help: https://docs.google.com/spreadsheets/d/1aAv3KuQNvrMHC-xFDP2VpLQKLJZs-8hXj-MIJ3k6bvY/edit#gid=0 
@NerdyProjects @c-w yeahh concerning the notification when you want to be informed about something that will happend soon the notification should come, but if the event is passed already when you login next time, than you should not see the notification anymore. E.g. when you setup the search for a food basket with vegan organic food in a range of 10km - the notification should only be there as long as nobody else claimed the basket - same could be an urgent food pick up for everyone on the team, this notificaction should also be gone when somebody of the store team members took the slot to pick food up. HOpe that was clear, if not I come down ;)

**Comment by c-w** [comment]
The use-cases in the document mostly look solvable via the search approach, so I'd say that we have an implementation on our hands.

Endpoints:
- `GET /users/notifications` lists all the active notifications for the currently logged in user.
- `POST {"query": "/search?the=query&defining=the&notification=goes&here"} /users/notifications` creates a new notification for something definable via search.

Pseudo-code implementation:
```python
class Notification(ModelBase):
    user = ForeignKey('yunity.User')
    query = TextField()
    state = JSONField()


def create_notification(user, query):
    state = execute_search(query)
    Notification.objects.create(user_id=user, query=query, state=state)

def list_notifications(user):
    notifications = Notification.objects.filter(user_id=user).all()
    for notification in notifications:
        state = execute_search(notification.query)
        if state != notification.state:
            notification.state = state
            yield notification
```

On page-load, we call `list_notifications` and display the results. We also set up a timer to call `list_notifications` every ~5 minutes and update the notifications in the UI.

**Open question**: how do we render the notification in the UI, i.e. how is the UI able to distinguish between a food-basket, wall post, etc?

**Comment by raphaelfellmer** [comment]
we talk about it later ok Clemens? or do you need to have the open questoin answered now?

**Comment by c-w** [comment]
@raphaelfellmer: How do you see the user interaction to create a notification? Roughly speaking, would the following two cover the interactions you're envisioning:
- A button on a group/event/user saying "follow"
- A search with a button for "Tell me when this is available"

**Comment by c-w** [comment]
Had a conversation with @raphaelfellmer. There are two classes of interactions:

1. Setting up a notification rooted on some sort of object: follow a user, follow a group, follow an event, follow a food-basket, etc.
2. Setting up a notification based on a search: alert me when an item like this becomes available.

This gives us the following option for rendering the notifications:

- Add a `context :: BaseModel` field to the Notification.
- When we set up a notification of type 1, set the context to the id of the object.
- When we set up a notification of type 2, set the context to null.
- We render a non-null context using the information from the context.
- We render a null-context as a search alert.

**Comment by nicksellen** [comment]
Notification settings also come with some options: see https://github.com/yunity/yunity-core/wiki/Group#notifications

**Comment by raphaelfellmer** [comment]
Dear Clemens, 

the 2nd class you described: "Setting up a notification based on a search: alert me when an item like this becomes available." can also be a notification which has a ending time, e.g. in a store where I pick up they need somebody urgently to pick up. I get a notification which will disappear when somebody else took the "job" (pickup). Or another example, I get a notification that "in hour you have an pick-up schedule" or something like this, this notification will than be also deleted when the event (pick-up) is over.
Hope that clarifies the notifications which come and go again a little bit more. 
love raphael
