### ISSUE TITLE
As a developer, I want to add unit tests for the API

### ISSUE THREAD

**Issue by tiltec** [yunity/yunity-core#81]
We should figure out how to have nice unit tests for API

**Comment by c-w** [comment]
One pattern I've seen used for this is to have some folders with test data that populate the database, some test requests, and some expected response.

```
tests/
`-- api
    |-- endpoint-1
    |   |-- test-1
    |   |   |-- data.json
    |   |   |-- request.json
    |   |   `-- response.json
    |   `-- test-2
    |       |-- data.json
    |       |-- request.json
    |       `-- response.json
    `-- endpoint-2
        |-- test-1
        |   |-- data.json
        |   |-- request.json
        |   `-- response.json
        `-- test-2
            |-- data.json
            |-- request.json
            `-- response.json
```

Adding a new unit test then only requires adding some data/request/response files.

**Comment by c-w** [comment]
Even better: use a `data.py` instead of `data.json` -- this lets us leverage Django's ORM to create data in a nice way and also gives us data re-use for free (e.g. most tests just need simple data so we can have some `common_data.py` that is imported by the individual tests's `data.py` files).

**Comment by c-w** [comment]
By the way, we should also set up the Django test runner to run [doctests](https://docs.python.org/3/library/doctest.html).

**Comment by c-w** [comment]
`./manage.py test` now runs the integration tests that are reflectively created from the data in `yunity/resources/tests/integration/`
