### ISSUE TITLE
Replace crossbar.io realtime backend

### ISSUE THREAD

**Issue by tiltec** [yunity/yunity-core#83]
As there have been some issues with the crossbar authorization, Nick proposed to replace the crossbar.io server

**Comment by tiltec** [comment]
[Taiga.io]https://github.com/taigaio/taiga-back/blob/master/taiga/events/backends/postgresql.py uses [postgresql notify]http://www.postgresql.org/docs/9.4/static/sql-notify.html
This essentially enables to push notifications over a channel to clients. Notifications can contain a payload. I am not sure why we would need something like this, a simple HTTP endpoint on a NodeJS communication server would be enough.

**Comment by nicksellen** [comment]
I love postgres notify stuff, but I don't think it offers anything here. It's very nice combined with db triggers though (e.g. publish event when a row is created/updated/deleted). But one also has to be careful as if the listener is disconnected there is no mechanism to store the messages.

**Comment by nicksellen** [comment]
Done, implemented in https://github.com/yunity/yunity-sockets
