### ISSUE TITLE
Integrate redis socket.io server connection in django

### ISSUE THREAD

**Issue by NerdyProjects** [yunity/yunity-core#84]
in yunity-sockets we now have an in-between socket server that serves websockets to the client.

It supports multiple sessions per client. A client is detected via its session ID.

The Django Application needs to publish session -> User ID mappings to the socket server and can then publish arbitrary json messages to each user based on a user ID. The Socket server multicasts this to every session which belongs to that user.

Future extension to global data is possible.

This task is about integrating the django part. A pre-existing library "SharedSession" can be used as a base.

**Comment by nicksellen** [comment]
The session->userid mapping is to be published to redis, not directly to socket.io.

See https://github.com/yunity/yunity-sockets#redis-sessions for the idea
