### ISSUE TITLE
As a developer, I want to sanitize user entered data

### ISSUE THREAD

**Issue by tiltec** [yunity/yunity-core#88]
for example, chat messages should escape HTML code, but allow most of UTF8 except for control characters and similar.
Django/Python should have a package for this.

**Comment by c-w** [comment]
I say that data cleanup should happen in the front-end. The back-end then simply rejects any malformed data or stores well-formed data in the database.

**Comment by nicksellen** [comment]
There might end up a few places where this informal data schema gets defined:
- frontend user interface (so we know how to render forms, and do any clientside validation)
- elasticsearch mappings (so we know how to correctly index the metadata)
- the backend validation (so it can reject naughty data)

The holy grail for me is to have one place where the data schema is defined, and then everywhere else can derive what they need from it, this is quite abstract though and a lot of work to get it right.

Also, to clarify are we talking about the `metadata` fields, db columns, or both?
