### ISSUE TITLE
As a user, I want to be able to request an item

### ISSUE THREAD

**Issue by c-w** [yunity/yunity-core#95]
Tom is hungry and would like a banana. Tom goes on yunity.org and searches for a banana but no one is offering any close to him. So Tom creates a request for a banana.

Later, Dan wants to offer a banana on yunity.org. While creating the offer for the banana, Dan sees Toms earlier ask and instead of creating a new offer, he just fulfills Tom's request instead. Tom now gets a banana, Dan doesn't have to wait to shift his food and everyone is happy.

**Comment by tiltec** [comment]
https://trello.com/c/VECjN8r4/76-i-5-as-a-user-i-want-to-make-a-request-on-the-item-page-for-the-item-so-that-the-system-knows-that-i-am-interested-in-that-item
